ALTER TABLE users ADD COLUMN deleted_at DATETIME NULL;
ALTER TABLE courses ADD COLUMN deleted_at DATETIME NULL;
ALTER TABLE exams ADD COLUMN deleted_at DATETIME NULL;
ALTER TABLE public_exams ADD COLUMN deleted_at DATETIME NULL;
